# Generated by Django 5.1.7 on 2025-04-26 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_specialty_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='common.program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'избранное',
                'verbose_name_plural': 'элемент избранного',
                'unique_together': {('account',)},
            },
        ),
    ]
