# Generated by Django 5.1.7 on 2025-04-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_specialty_duration'),
        ('wishlist', '0002_alter_wishlistitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='education_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='common.educationplace', verbose_name='ВУЗ'),
            preserve_default=False,
        ),
    ]
