# Generated by Django 5.1.7 on 2025-04-28 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_specialty_duration'),
        ('wishlist', '0003_wishlistitem_education_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('account', 'education_place')},
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='program',
        ),
    ]
