# Generated by Django 5.1.7 on 2025-05-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='education_place',
            new_name='program',
        ),
    ]
