# Generated by Django 5.1.7 on 2025-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_education_place_application_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
    ]
