# Generated by Django 5.1.7 on 2025-05-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='attachments',
        ),
    ]
