# Generated by Django 5.1.7 on 2025-05-15 09:55

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_comment_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment_file',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.application_files_upload_to, verbose_name='закрепленный файл комментария'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.application_files_upload_to, verbose_name='оффер'),
        ),
    ]
