# Generated by Django 5.1.7 on 2025-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_application_name_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'черновик'), ('IN_PROGRESS', 'в работе'), ('DENIED', 'отказано'), ('ACCEPTED', 'принято'), ('FOR_REVISION', 'на доработку'), ('FOR_CONSIDERATION', 'на рассмотрении'), ('FOR_ADMINS', 'для админов')], db_index=True, max_length=255, verbose_name='статус'),
        ),
    ]
