# Generated by Django 5.1.7 on 2025-04-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название страны')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название города')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='EducationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название учебного заведения')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'учебное заведение',
                'verbose_name_plural': 'учебные заведения',
            },
        ),
    ]
