# Generated by Django 5.1.7 on 2025-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='название города'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='название страны'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='название учебного заведения'),
        ),
    ]
