# Generated by Django 5.1.7 on 2025-04-16 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_city_name_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationplace',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
