# Generated by Django 5.1.7 on 2025-04-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_educationplace_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationplace',
            name='is_for_admission',
            field=models.BooleanField(default=True, verbose_name='доступен для поступления'),
        ),
    ]
