# Generated by Django 5.1.7 on 2025-04-19 18:17

import ckeditor.fields
import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_educationplace_is_for_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Группа специальностей',
                'verbose_name_plural': 'Группы специальностей',
            },
        ),
        migrations.AddField(
            model_name='educationplace',
            name='foundation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата основания'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.models.education_place_path, verbose_name='фото ВУЗа'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=common.models.education_place_path, verbose_name='лого'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='prices_data',
            field=models.JSONField(blank=True, null=True, verbose_name='цены'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='common.country', verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_places', to='common.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='is_for_admission',
            field=models.BooleanField(default=True, verbose_name='доступно для поступления'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(choices=[('BACHELOR', 'bachelor'), ('MASTERS', 'masters'), ('MBA', 'mba'), ('PHD', 'phd')], max_length=128, verbose_name='название программы')),
                ('description_general', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание общее')),
                ('description_academic', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание академ требований')),
                ('description_scholarship', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание стипендии')),
                ('description_prices', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание цен')),
                ('duration_years', models.PositiveIntegerField(verbose_name='Длительность обучения(лет)')),
                ('admission_deadline', models.DateField(blank=True, null=True, verbose_name='дедлайн подачи')),
                ('specialty_durations', models.JSONField(blank=True, null=True, verbose_name='мин макс длительность обучения специальностей')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='стоимость обучения')),
                ('language', models.CharField(choices=[('ENGLISH', 'english'), ('FRENCH', 'french'), ('SPANISH', 'spanish'), ('RUSSIAN', 'russian')], max_length=128, verbose_name='язык обучения')),
                ('format', models.CharField(choices=[('ONLINE', 'online'), ('OFFLINE', 'offline')], max_length=128, verbose_name='формат обучения')),
                ('education_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='degrees', to='common.educationplace', verbose_name='учебное заведение')),
            ],
            options={
                'verbose_name': 'программа образования',
                'verbose_name_plural': 'программы образования',
                'unique_together': {('education_place', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='название дедлайна')),
                ('due_to', models.DateField(verbose_name='до:')),
                ('education_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='common.educationplace', verbose_name='учебное заведение')),
            ],
            options={
                'verbose_name': 'дедлайн',
                'verbose_name_plural': 'дедлайны',
                'unique_together': {('education_place', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='тип расходов')),
                ('price_per_year_text', models.CharField(max_length=255, verbose_name='цена')),
                ('education_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='common.educationplace', verbose_name='учебное заведение')),
            ],
            options={
                'verbose_name': 'расход',
                'verbose_name_plural': 'расходы',
                'unique_together': {('education_place', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AcademicRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='название требования')),
                ('treshold', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='пороговый балл')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_requirements', to='common.program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'академические требования',
                'verbose_name_plural': 'академическое требование',
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='название специальности')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание')),
                ('education_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialities', to='common.educationplace', verbose_name='учебное заведение')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialities', to='common.program', verbose_name='программа')),
                ('specialty_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialities', to='common.specialtygroup', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'специальности',
                'unique_together': {('education_place', 'program', 'name')},
            },
        ),
    ]
