# Generated by Django 5.1.7 on 2025-04-16 18:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_educationplace_is_for_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='common.country', verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_places', to='common.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='is_for_admission',
            field=models.BooleanField(default=True, verbose_name='доступно для поступления'),
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='название специальности')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание')),
                ('degree', models.CharField(choices=[('BACHELOR', 'bachelor'), ('MASTERS', 'masters'), ('MBA', 'mba')], max_length=128, verbose_name='степень')),
                ('education_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialities', to='common.educationplace', verbose_name='универ')),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'специальности',
                'unique_together': {('education_place', 'degree', 'name')},
            },
        ),
    ]
