# Generated by Django 5.1.7 on 2025-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_specialtygroup_educationplace_foundation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='длительность(лет)'),
            preserve_default=False,
        ),
    ]
