# Generated by Django 5.1.7 on 2025-04-28 11:54

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_specialty_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationplace',
            name='description',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description_scholarship',
        ),
        migrations.AddField(
            model_name='deadline',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='common.program', verbose_name='программа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationplace',
            name='campus_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание кампуса'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='general_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='основное описание'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на страницу ВУЗа'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='scholarship_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание стипендии'),
        ),
        migrations.AddField(
            model_name='expense',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='common.program', verbose_name='программа'),
            preserve_default=False,
        ),
    ]
