# Generated by Django 5.1.7 on 2025-04-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_educationplace_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deadline',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('program', 'name')},
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='education_place',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='education_place',
        ),
    ]
