# Generated by Django 5.1.7 on 2025-04-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_deadline_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='admission_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='дедлайн подачи'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='стоимость обучения'),
        ),
    ]
