# Generated by Django 5.1.7 on 2025-04-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_specialty_admission_deadline_specialty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='education_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='common.educationplace', verbose_name='учебное заведение'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='common.program', verbose_name='программа'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='specialty_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='common.specialtygroup', verbose_name='группа'),
        ),
    ]
