# Generated by Django 5.1.7 on 2025-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_specialty_education_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrequirement',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='название требования'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='название города'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='название страны'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='название дедлайна'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='foundation_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='is_for_admission',
            field=models.BooleanField(db_index=True, default=True, verbose_name='доступно для поступления'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='тип расходов'),
        ),
        migrations.AlterField(
            model_name='program',
            name='admission_deadline',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='дедлайн подачи'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_years',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Длительность обучения(лет)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='format',
            field=models.CharField(choices=[('ONLINE', 'online'), ('OFFLINE', 'offline')], db_index=True, max_length=128, verbose_name='формат обучения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'english'), ('FRENCH', 'french'), ('SPANISH', 'spanish'), ('RUSSIAN', 'russian')], db_index=True, max_length=128, verbose_name='язык обучения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(choices=[('BACHELOR', 'bachelor'), ('MASTERS', 'masters'), ('MBA', 'mba'), ('PHD', 'phd')], db_index=True, max_length=128, verbose_name='название программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='стоимость обучения'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='duration',
            field=models.PositiveIntegerField(db_index=True, verbose_name='длительность(лет)'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='название специальности'),
        ),
    ]
