# Generated by Django 5.1.7 on 2025-05-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_academicrequirement_name_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationplace',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='название учебного заведения'),
        ),
        migrations.AlterField(
            model_name='specialtygroup',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='название'),
        ),
    ]
