# Generated by Django 5.1.7 on 2025-06-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_educationplace_name_alter_specialtygroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrequirement',
            name='treshold',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='пороговый балл'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='стоимость обучения'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='стоимость обучения'),
        ),
    ]
