# Generated by Django 5.1.7 on 2025-06-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_academicrequirement_treshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationplace',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='название учебного заведения'),
        ),
    ]
