# Generated by Django 5.1.7 on 2025-06-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_educationplace_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationplace',
            name='foundation_date',
        ),
        migrations.AddField(
            model_name='educationplace',
            name='foundation_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Год основания'),
        ),
        migrations.AlterField(
            model_name='program',
            name='format',
            field=models.CharField(choices=[('ONLINE', 'online'), ('OFFLINE', 'offline'), ('HYBRID', 'hybrid')], db_index=True, max_length=128, verbose_name='формат обучения'),
        ),
    ]
