# Generated by Django 5.1.7 on 2025-06-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_educationplace_foundation_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together={('program', 'name')},
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='education_place',
        ),
    ]
