# Generated by Django 5.1.7 on 2025-06-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_specialty_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrequirement',
            name='treshold',
            field=models.CharField(max_length=255, verbose_name='пороговый балл'),
        ),
    ]
