# Generated by Django 5.1.7 on 2025-04-06 18:29

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='имя')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='фамилия')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='отчество')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер телефона')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_path, verbose_name='аватар')),
                ('is_staff', models.BooleanField(default=False, verbose_name='статус админа')),
                ('is_active', models.BooleanField(default=True, verbose_name='статус активности')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='статус суперпользователя')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.city', verbose_name='город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.country', verbose_name='страна')),
                ('education_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.educationplace', verbose_name='учебное заведение')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'аккаунт',
                'verbose_name_plural': 'аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='название файла/сертификата')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='оценка')),
                ('file', models.FileField(blank=True, null=True, upload_to=accounts.models.attachment_path, verbose_name='файл')),
                ('meta', models.JSONField(blank=True, null=True, verbose_name='дополнительно')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
