# Generated by Django 5.1.7 on 2025-04-14 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'документ', 'verbose_name_plural': 'документы'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='название файла/сертификата'),
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('account', 'name')},
        ),
    ]
