# Generated by Django 5.1.7 on 2025-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_attachment_options_alter_attachment_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='degree',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'bachelor'), ('MASTERS', 'masters'), ('MBA', 'mba')], max_length=128, null=True, verbose_name='академическая степень'),
        ),
    ]
