# Generated by Django 5.1.7 on 2025-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='grade',
        ),
        migrations.AddField(
            model_name='account',
            name='duolingo_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='оценка DUOLINGO'),
        ),
        migrations.AddField(
            model_name='account',
            name='gmat_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='оценка GMAT'),
        ),
        migrations.AddField(
            model_name='account',
            name='gpa_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='оценка GPA'),
        ),
        migrations.AddField(
            model_name='account',
            name='gre_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='оценка GRE'),
        ),
        migrations.AddField(
            model_name='account',
            name='ielts_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='оценка IELTS'),
        ),
        migrations.AddField(
            model_name='account',
            name='sat_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='оценка SAT'),
        ),
        migrations.AddField(
            model_name='account',
            name='toefl_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='оценка TOEFL'),
        ),
    ]
