# Generated by Django 5.1.7 on 2025-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_attachment_grade_account_duolingo_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='degree',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'bachelor'), ('MASTERS', 'masters'), ('MBA', 'mba'), ('PHD', 'phd')], max_length=128, null=True, verbose_name='академическая степень'),
        ),
    ]
