# Generated by Django 5.1.7 on 2025-05-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_degree'),
        ('applications', '0004_remove_application_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='applications.application', verbose_name='заявка'),
        ),
    ]
