# Generated by Django 5.1.7 on 2025-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_attachment_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='meta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='дополнительно'),
        ),
    ]
