# Generated by Django 5.1.7 on 2025-05-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_attachment_unique_together'),
        ('common', '0012_alter_educationplace_name_alter_specialtygroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='common.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='common.country', verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='common.educationplace', verbose_name='учебное заведение'),
        ),
    ]
