# Generated by Django 5.1.7 on 2025-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_city_alter_account_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название файла/сертификата'),
        ),
    ]
