# Generated by Django 5.1.7 on 2025-05-06 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0006_alter_comment_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('type', models.CharField(choices=[('SUCCESS', 'успех'), ('FAILURE', 'провал')], max_length=255, verbose_name='тип')),
                ('content', models.TextField(verbose_name='контент')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.application', verbose_name='заявка')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
            },
        ),
    ]
