# Generated by Django 5.1.7 on 2025-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='прочитано'),
        ),
    ]
