# Generated by Django 5.1.7 on 2025-05-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(db_index=True, default=False, verbose_name='прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DRAFT', 'черновик'), ('IN_PROGRESS', 'в работе'), ('DENIED', 'отказано'), ('ACCEPTED', 'принято'), ('FOR_REVISION', 'на доработку'), ('FOR_CONSIDERATION', 'на рассмотрении')], db_index=True, max_length=255, verbose_name='тип'),
        ),
    ]
