# Generated by Django 5.1.7 on 2025-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_is_seen_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='контент'),
        ),
    ]
