# Generated by Django 5.1.7 on 2025-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DRAFT', 'черновик'), ('IN_PROGRESS', 'в работе'), ('DENIED', 'отказано'), ('ACCEPTED', 'принято'), ('FOR_REVISION', 'на доработку'), ('FOR_CONSIDERATION', 'на рассмотрении'), ('FOR_ADMINS', 'для админов')], db_index=True, max_length=255, verbose_name='тип'),
        ),
    ]
